### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by DannyParker0001** [SwagSoftware/Kisak-Strike#12]
Hello Mr. Gentoomen, I forked, I tried for 7 hours, I got nowhere. I give up.

I tried with Clang, Clang-CL and MSVC. Clang showed the most promise. I've undone all my code changes, and commited just the cmake ones on my fork if you wanted to give that a shot.

### Use GCC
My Cygwin install is broken, GCC is a fucking pain on windows, I would rather not, but if you cbf doing clang support then aight.

### Why not just use linux?
Because I am a windows baby, [waaaaahhhhhhhhhh](https://www.youtube.com/watch?v=tRZPBJewHYw)

**Comment by quadruple-damage** [comment]
https://wiki.gentoo.org/wiki/Installation

**Comment by koutsie** [comment]
https://wiki.archlinux.org/index.php/Installation_Guide

**Comment by FilipeSilvens** [comment]
![image](https://user-images.githubusercontent.com/21077476/103696370-20dd6100-4f96-11eb-81f4-e81788c8b273.png)

**Comment by quadruple-damage** [comment]
Alternatively, if you think Gentoo is to hard https://www.debian.org/releases/stable/installmanual

**Comment by koutsie** [comment]
Or if you wanna get running in no time; https://artixlinux.org/

**Comment by DannyParker0001** [comment]
I dual boot with arch already

**Comment by quadruple-damage** [comment]
> I dual boot with arch already

Use arch.

**Comment by koutsie** [comment]
Also yeah. 
RTFRM.MD
https://github.com/SwagSoftware/Kisak-Strike/issues/12#issuecomment-754885761

**Comment by HappyDOGE** [comment]
I’ve actually managed to run KS on Windows however it only worked with vgui since scaleform crashed and rocketui implementation is gl-specific, also the thing is hacked beyond repair so I just abandoned it

**Comment by LWSS** [comment]
@HappyDOGE Running the VPC is not the same as cmake, that shit is garbage and I don't touch it, it builds for the intel nocona series and links with about 30 prebuilt blobs. What you should have done is port the necessary cmake files over to windows, but I get that the Windows-user attention span is short and it was 20 minutes since your last fortnite session.

**Comment by HappyDOGE** [comment]
@LWSS Where exactly did I say that I used VPC?

**Comment by LWSS** [comment]
Just a guess; I was giving you some shit.

I'm serious about not supporting windows though. The last thing we need is a bunch of normies flooding in and ruining our comfy project.

There's a nice beginner-friendly linux distro called Ubuntu, you should try it out, if you need some help you can even ask in here.

**Comment by nn15** [comment]
> https://wiki.archlinux.org/index.php/Installation_Guide

hahaha
