### ISSUE TITLE
Tag "refs/heads/master" causes "error: dst refspec refs/heads/master matches more than one"

### ISSUE THREAD

**Issue by r-a-sattarov** [SwagSoftware/Kisak-Strike#25]
Please remove this tag because it causes errors when trying to make "git push".

**error: src refspec refs/heads/master matches more than one**
**error: dst refspec refs/heads/master matches more than one**

- https://github.com/SwagSoftware/Kisak-Strike/releases/tag/refs%2Fheads%2Fmaster

**Comment by PANCHO7532B** [comment]
Yeah... sorry about that. It's just a mis-configuration of the CI/CD workflow that it went along unnoticed. Already pushed a fix so further Pull Requests, Forks and Releases should compile. Just you need to re-sync your fork for the changes to apply.
