### ISSUE TITLE
add arm64 support？

### ISSUE THREAD

**Issue by nn15** [SwagSoftware/Kisak-Strike#30]
is there have any closed source libs？

**Comment by r-a-sattarov** [comment]
> is there have any closed source libs？

Hi! Try looking at this repo - https://github.com/nillerusr/source-engine
@nillerusr added support for ARM (Android).

**Comment by nn15** [comment]
> > is there have any closed source libs？
> 
> 
> 
> Hi! Try looking at this repo - https://github.com/nillerusr/source-engine
> 
> @nillerusr added support for ARM (Android).

it use waifu build system
