### ISSUE TITLE
Missing libsteam_api.so

### ISSUE THREAD

**Issue by Nord1cWarr1or** [SwagSoftware/Kisak-Strike#44]
Hello!

I installed the game from Releases, then did all the steps from the "postbuild" section in the readme. But when I try to start the game, I get an error: `Failed to load the launcher(bin/linux64/launcher_client.so) (libsteam_api.so: cannot open shared object file: No such file or directory)`.

I tried putting libsteam_api.so from depotID 734, but it still doesn't work.

**Comment by Nord1cWarr1or** [comment]
@nn-firc can you please explain in more detail? As far as I know, environment variables are used to compile, and I installed the release.

**Comment by nn-firc** [comment]
> @nn-firc can you please explain in more detail? As far as I know, environment variables are used to compile, and I installed the release.

have you set LD_LIBRARY_PATH env to your game bin path?

**Comment by Nord1cWarr1or** [comment]
> have you set LD_LIBRARY_PATH env to your game bin path?

no, I don't know about it. After your reply, I tried to do so. But, the archive from the "releases" does not contain libsteam_api.so, where can I get it?

**Comment by SanyaSho** [comment]
you can use goldberg emulator or copy libsteam_api from binaries depot

**Comment by nn-firc** [comment]
> > have you set LD_LIBRARY_PATH env to your game bin path?
> 
> no, I don't know about it. After your reply, I tried to do so. But, the archive from the "releases" does not contain libsteam_api.so, where can I get it?

It's already in the source code's lib/public/linux64 dir.

**Comment by Nord1cWarr1or** [comment]
Sorry for the long response, guys. I set the LD_LIBRARY_PATH variable and tried to take the file from depot as well as from source, but in both cases I get the following error: `Failed to load the launcher(bin/linux64/launcher_client.so) (libsteam_api.so: wrong ELF class: ELFCLASS32)`

**Comment by SanyaSho** [comment]
u need libsteam_api64.so lol

**Comment by Nord1cWarr1or** [comment]
> u need libsteam_api64.so lol

You're right, I accidentally took a 32-bit file.

I decided to do it all over again to make sure I got it right.
So, I did the following:
1. I downloaded and extracted the files from Release.
2. Downloaded and placed all the files from the 731 depot and only the necessary files from the 734 depot.
3. Placed the files from "Kisak Strike Files".
4. Put all the .so files from "lib/public/linux64/" of that repository into "game/bin/linux64/" folder
5. Set LD_LIBRARY_PATH to ".../game/bin/linux64/

But now I just get SIGILL:
```
[⚡] × ./csgo_linux64
fish: Job 1, './csgo_linux64' terminated by signal SIGILL (Illegal instruction)
````
What did I do wrong now?

**Comment by nn-firc** [comment]
> > u need libsteam_api64.so lol
> 
> You're right, I accidentally took a 32-bit file.
> 
> I decided to do it all over again to make sure I got it right. So, I did the following:
> 
> 1. I downloaded and extracted the files from Release.
> 2. Downloaded and placed all the files from the 731 depot and only the necessary files from the 734 depot.
> 3. Placed the files from "Kisak Strike Files".
> 4. Put all the .so files from "lib/public/linux64/" of that repository into "game/bin/linux64/" folder
> 5. Set LD_LIBRARY_PATH to ".../game/bin/linux64/
> 
> But now I just get SIGILL:
> 
> ```
> [⚡] × ./csgo_linux64
> fish: Job 1, './csgo_linux64' terminated by signal SIGILL (Illegal instruction)
> ```
> 
> What did I do wrong now?

build it from source code
