### ISSUE TITLE
Hehe

### ISSUE THREAD

**Issue by recoil23** [SwagSoftware/Kisak-Strike#49]
I like how it all started with the leak and you rebuilding the game and they invited you in. Master G 😄

**Comment by recoil23** [comment]
Good luck in future bruh make us new half life 3 xd

**Comment by LWSS** [comment]
to be clear, I do not work at Valve

**Comment by PiMoNFeeD** [comment]
amazing issue

**Comment by NeuroArter** [comment]
xD

**Comment by quad-damage** [comment]
> to be clear, I do not work at Valve

Do not believe him. There is plenty of proof around that he is a certain someone whose name starts with a 'k' and ends with 'isak"

**Comment by LWSS** [comment]
actually @kisak-valve doesn't even work at Valve, he's like a slave contractor and gentoo volunteer

**Comment by nn-firc** [comment]
?
