### ISSUE TITLE
Unable to load module rocketui_client.so!

### ISSUE THREAD

**Issue by infdivzero** [SwagSoftware/Kisak-Strike#55]
Built with ``cmake -DCMAKE_BUILD_TYPE=Release .. -DUSE_KISAK_PHYSICS=1 -DUSE_ROCKETUI=1``.
```
SDL video target is 'x11'
This system supports the OpenGL extension GL_EXT_framebuffer_object.
...
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
Module rocketui_client.so failed to load! Error: ((null))
AppFramework : Unable to load module rocketui_client.so!
Unable to load interface RocketUI001 from rocketui_client.so, requested from EXE.
```
I have added the files from Kisak-Strike-Files to the game directory as-is, and the steam content.

Top level directory:
```
../game
├── bin/
├── csgo/
├── platform/
├── asan.sh
├── chrome.pak
├── csgo_linux64
├── csgo.sh
├── README.md
├── srcds_linux
└── thirdpartylegalnotices.doc
```

**Comment by LWSS** [comment]
did it build the .so?

**Comment by infdivzero** [comment]
Yes, ``bin/linux64/rocketui_client.so`` appears valid according to readelf. I've set LD_LIBRARY_PATH to bin/linux64 which helped it load libtcmalloc_minimal.so.

**Comment by LWSS** [comment]
do `ldd -r` on it, see if anything's missing

**Comment by infdivzero** [comment]
RmlCore was missing, copying it over got it to run.

**Comment by PlatonNovikov** [comment]
What is RmlCore?
